
import { User } from './types';

export const MOCK_USER_ID = 0;

export const GENRES = [
  'Phonk', 'Hip-Hop', 'Electronic', 'Lo-Fi', 'Rock', 'Ambient', 'Techno', 'Pop'
];

export const INITIAL_USER: User = {
  id: 0,
  username: '',
  firstName: '',
  lastName: '',
  photoUrl: '',
  bio: '',
  links: {},
  stats: {
    uploads: 0,
    likesReceived: 0,
    totalPlays: 0,
  },
};

export const TELEGRAM_BOT_TOKEN = '8597639400:AAGg76KAn5onhXZGLaWQx6jDJbaBah4emBg'; 
export const TELEGRAM_CHAT_ID = '@clan_mori'; 
export const TELEGRAM_GROUP_LINK = 'https://t.me/clan_mori';
export const TELEGRAM_APP_LINK = 'https://t.me/morimusics_bot/app';

export type Language = 'en' | 'ru';

export const TRANSLATIONS = {
  en: {
    app_initializing: 'Initializing Mori',
    nav_feed: 'Feed',
    nav_charts: 'Charts',
    nav_upload: 'Upload',
    nav_profile: 'Profile',
    nav_concerts: 'Rooms',
    
    feed_new: 'New',
    feed_hot: 'Hot',
    feed_loading: 'Loading beats...',
    feed_search_placeholder: 'Search tracks, artists, genres...',
    feed_no_results: 'No tracks found for that search.',
    feed_empty: 'No tracks found. Upload the first one!',
    
    track_share: 'Share Track',
    track_copied: 'Copied!',
    track_download: 'Download Audio',
    track_downloading: 'Downloading...',
    track_delete: 'Delete',
    track_delete_confirm: 'Are you sure you want to delete this track? This cannot be undone.',
    track_listen_text: 'Listen to',
    track_by: 'by',
    track_plays: 'plays',
    track_comment_placeholder: 'Add a comment...',
    track_comment_post: 'Post',
    track_no_comments: 'No comments yet. Be the first!',
    track_add_playlist: 'Add to Playlist',
    track_added_playlist: 'Added to Playlist',
    
    snippet_promo: 'Visual card for your stories and friends',
    snippet_save: 'Save',
    snippet_send: 'Send',
    snippet_close: 'Close Preview',
    snippet_title: 'Visual Snippet',
    
    charts_title: 'Top Charts',
    charts_week: 'Top of Week',
    charts_month: 'Top of Month',
    charts_loading: 'Loading charts...',
    charts_empty: 'Not enough data for this period yet.',
    
    upload_title: 'Upload',
    upload_mode_single: 'Single Track',
    upload_mode_album: 'Album / EP',
    upload_cover_change: 'Change',
    upload_cover_add: 'Add Cover',
    upload_audio_remove: 'Remove',
    upload_audio_placeholder: 'Select Audio',
    upload_audio_multi_placeholder: 'Select Tracks',
    upload_label_title: 'Title',
    upload_label_album_title: 'Album Title',
    upload_placeholder_title: 'Track Name',
    upload_placeholder_album_title: 'Album Name',
    upload_label_genre: 'Genre',
    upload_label_desc: 'Description',
    upload_placeholder_desc: 'Tell us about your release...',
    upload_btn: 'Publish',
    upload_btn_album: 'Publish Album',
    upload_btn_loading: 'Uploading...',
    upload_btn_loading_album: 'Uploading Album...',
    upload_access_denied: 'Access Denied',
    upload_sub_required: 'To upload tracks, you must be subscribed to our channel',
    upload_sub_btn: 'Subscribe Now?',
    upload_magic_ai: 'Magic AI',
    
    profile_loading: 'Loading profile...',
    profile_not_found: 'User not found',
    profile_tracks: 'Tracks',
    profile_likes: 'Likes',
    profile_history: 'History',
    profile_playlists: 'Playlists',
    profile_saved_playlists: 'Saved Playlists',
    profile_create_playlist: 'New Playlist',
    profile_playlist_name: 'Playlist Name',
    profile_playlist_create_btn: 'Create',
    profile_playlist_cancel: 'Cancel',
    profile_playlist_save: 'Save to Library',
    profile_playlist_unsave: 'Remove from Library',
    profile_plays: 'Plays',
    profile_no_links: 'No social links added.',
    profile_my_tracks: 'My Tracks',
    profile_user_tracks: "'s Tracks",
    profile_no_tracks: 'No tracks available.',
    profile_no_playlists: 'No playlists created.',
    profile_no_saved_playlists: 'No saved playlists.',
    profile_bio_placeholder: 'Add a bio in settings...',
    profile_no_bio: 'No bio.',
    profile_artist_hub: 'Artist Hub',
    profile_history_empty: 'Empty history',
    profile_playlist_empty: 'No tracks here',
    
    settings_title: 'Edit Profile',
    settings_language: 'Language',
    settings_header: 'Profile Header',
    settings_header_add: 'Add Header Image',
    settings_avatar_hint: 'Tap avatar to change',
    settings_public_info: 'Public Info',
    settings_firstname: 'First Name',
    settings_lastname: 'Last Name',
    settings_bio: 'Bio',
    settings_bio_placeholder: 'Tell the world about your music...',
    settings_socials: 'Social Links',
    settings_other_placeholder: 'Other (VK, YouTube, etc.)',
    settings_save: 'Save Changes',
    settings_saving: 'Saving...',
    settings_error: 'Failed to save changes.',
    
    concerts_title: 'DJ Rooms',
    concerts_subtitle: 'Live synchronized radio',
    concerts_live_now: 'Live Sessions',
    concerts_upcoming: 'Upcoming Rooms',
    concerts_viewers: 'listeners',
    concerts_chat_placeholder: 'Say something...',
    concerts_empty: 'No active radio sessions.',
    concerts_end: 'Session Ended',
    concerts_create: 'Create Room',
    concerts_create_title: 'Room Title',
    concerts_create_cover: 'Room Cover',
    concerts_create_btn: 'Start Session',
    concerts_close: 'End Session',
    concerts_tab_chat: 'Radio Chat',
    concerts_tab_console: 'DJ Console',
    concerts_mic_title: 'On Air Mic',
    concerts_mic_desc: 'Broadcast your voice live',
    concerts_library_title: 'Radio Library',
    concerts_library_placeholder: 'Select Playlist...',
    concerts_create_label_track: 'Initial Track (Optional)',
    concerts_create_option_none: 'None / Live Mic',
    concerts_welcome_msg: 'Welcome! Session live.',
    concerts_on_air: 'ON AIR',
    concerts_streaming: 'Streaming',
    
    link_spotify: 'Spotify',
    link_soundcloud: 'SoundCloud',
    link_yandex: 'Yandex Music',
    link_vk: 'VK',
    link_youtube: 'YouTube',
    link_website: 'Website',
  },
  ru: {
    app_initializing: 'Инициализация Mori',
    nav_feed: 'Лента',
    nav_charts: 'Чарты',
    nav_upload: 'Загрузка',
    nav_profile: 'Профиль',
    nav_concerts: 'Комнаты',
    
    feed_new: 'Новое',
    feed_hot: 'Топ',
    feed_loading: 'Загрузка битов...',
    feed_search_placeholder: 'Поиск треков, артистов, жанров...',
    feed_no_results: 'Ничего не найдено по запросу.',
    feed_empty: 'Треков нет. Загрузи первый!',
    
    track_share: 'Поделиться',
    track_copied: 'Скопировано!',
    track_download: 'Скачать трек',
    track_downloading: 'Загрузка...',
    track_delete: 'Удалить',
    track_delete_confirm: 'Вы уверены, что хотите удалить этот трек? Это действие нельзя отменить.',
    track_listen_text: 'Слушай',
    track_by: 'от',
    track_plays: 'прослушиваний',
    track_comment_placeholder: 'Написать комментарий...',
    track_comment_post: 'Отпр.',
    track_no_comments: 'Комментариев нет. Будь первым!',
    track_add_playlist: 'В плейлист',
    track_added_playlist: 'Добавлено в плейлист',
    
    snippet_promo: 'Карточка для твоих сторис и друзей',
    snippet_save: 'Сохранить',
    snippet_send: 'Отправить',
    snippet_close: 'Закрыть превью',
    snippet_title: 'Визуальный сниппет',
    
    charts_title: 'Топ Чарты',
    charts_week: 'Топ Недели',
    charts_month: 'Топ Месяца',
    charts_loading: 'Загрузка чартов...',
    charts_empty: 'Недостаточно данных за этот период.',
    
    upload_title: 'Загрузка',
    upload_mode_single: 'Сингл',
    upload_mode_album: 'Альбом / EP',
    upload_cover_change: 'Изменить',
    upload_cover_add: 'Обложка',
    upload_audio_remove: 'Удалить',
    upload_audio_placeholder: 'MP3/WAV файл',
    upload_audio_multi_placeholder: 'Выбрать треки',
    upload_label_title: 'Название',
    upload_label_album_title: 'Название альбома',
    upload_placeholder_title: 'Название трека',
    upload_placeholder_album_title: 'Название альбома',
    upload_label_genre: 'Жанр',
    upload_label_desc: 'Описание',
    upload_placeholder_desc: 'Расскажи о своем релизе...',
    upload_btn: 'Опубликовать',
    upload_btn_album: 'Загрузить альбом',
    upload_btn_loading: 'Загрузка...',
    upload_btn_loading_album: 'Загрузка альбома...',
    upload_access_denied: 'Доступ запрещен',
    upload_sub_required: 'Чтобы загружать треки, вы должны быть подписаны на наш канал',
    upload_sub_btn: 'Подписаться?',
    upload_magic_ai: 'Магия AI',
    
    profile_loading: 'Загрузка профиля...',
    profile_not_found: 'Пользователь не найден',
    profile_tracks: 'Треки',
    profile_likes: 'Лайки',
    profile_history: 'История',
    profile_playlists: 'Плейлисты',
    profile_saved_playlists: 'Сохраненные плейлисты',
    profile_create_playlist: 'Новый плейлист',
    profile_playlist_name: 'Название плейлиста',
    profile_playlist_create_btn: 'Создать',
    profile_playlist_cancel: 'Отмена',
    profile_playlist_save: 'Сохранить себе',
    profile_playlist_unsave: 'Убрать из сохраненных',
    profile_plays: 'Прослушивания',
    profile_no_links: 'Ссылки не добавлены.',
    profile_my_tracks: 'Мои треки',
    profile_user_tracks: ': Треки',
    profile_no_tracks: 'Треков пока нет.',
    profile_no_playlists: 'Плейлистов пока нет.',
    profile_no_saved_playlists: 'Нет сохраненных плейлистов.',
    profile_bio_placeholder: 'Добавь описание в настройках...',
    profile_no_bio: 'Нет описания.',
    profile_artist_hub: 'Хаб артиста',
    profile_history_empty: 'История пуста',
    profile_playlist_empty: 'Здесь нет треков',
    
    settings_title: 'Редактировать',
    settings_language: 'Язык / Language',
    settings_header: 'Шапка профиля',
    settings_header_add: 'Добавить шапку',
    settings_avatar_hint: 'Нажми на фото, чтобы изменить',
    settings_public_info: 'Публичная информация',
    settings_firstname: 'Имя',
    settings_lastname: 'Фамилия',
    settings_bio: 'О себе',
    settings_bio_placeholder: 'Расскажи миру о своей музыке...',
    settings_socials: 'Соцсети',
    settings_other_placeholder: 'Другое (VK, YouTube и т.д.)',
    settings_save: 'Сохранить',
    settings_saving: 'Сохранение...',
    settings_error: 'Ошибка сохранения.',

    concerts_title: 'DJ Комнаты',
    concerts_subtitle: 'Синхронное радио в прямом эфире',
    concerts_live_now: 'В эфире',
    concerts_upcoming: 'Афиша комнат',
    concerts_viewers: 'слушателей',
    concerts_chat_placeholder: 'Написать в чат...',
    concerts_empty: 'Нет активных радио-сессий.',
    concerts_end: 'Сессия завершена',
    concerts_create: 'Создать комнату',
    concerts_create_title: 'Название комнаты',
    concerts_create_cover: 'Обложка комнаты',
    concerts_create_btn: 'Начать эфир',
    concerts_close: 'Завершить эфир',
    concerts_tab_chat: 'Чат радио',
    concerts_tab_console: 'DJ Консоль',
    concerts_mic_title: 'Микрофон в эфире',
    concerts_mic_desc: 'Транслируйте свой голос в реальном времени',
    concerts_library_title: 'Радио-библиотека',
    concerts_library_placeholder: 'Выбрать плейлист...',
    concerts_create_label_track: 'Стартовый трек (опц.)',
    concerts_create_option_none: 'Нет / Прямой эфир',
    concerts_welcome_msg: 'Добро пожаловать! Эфир запущен.',
    concerts_on_air: 'В ЭФИРЕ',
    concerts_streaming: 'Стриминг',

    link_spotify: 'Spotify',
    link_soundcloud: 'SoundCloud',
    link_yandex: 'Яндекс Музыка',
    link_vk: 'ВКонтакте',
    link_youtube: 'YouTube',
    link_website: 'Вебсайт',
  }
};
