
import { User } from './types';

export const MOCK_USER_ID = 0;

export const GENRES = [
  'Phonk', 'Hip-Hop', 'Electronic', 'Lo-Fi', 'Rock', 'Ambient', 'Techno', 'Pop'
];

export const INITIAL_USER: User = {
  id: 0,
  username: '',
  firstName: '',
  lastName: '',
  photoUrl: '',
  bio: '',
  links: {},
  stats: {
    uploads: 0,
    likesReceived: 0,
    totalPlays: 0,
  },
};

export const TELEGRAM_BOT_TOKEN = '8597639400:AAGg76KAn5onhXZGLaWQx6jDJbaBah4emBg'; 
export const TELEGRAM_CHAT_ID = '@clan_mori'; 
export const TELEGRAM_GROUP_LINK = 'https://t.me/clan_mori';
export const TELEGRAM_APP_LINK = 'https://t.me/morimusics_bot/app';

export type Language = 'en' | 'ru';

export const TRANSLATIONS = {
  en: {
    app_initializing: 'Initializing Mori',
    nav_feed: 'Feed',
    nav_charts: 'Charts',
    nav_upload: 'Upload',
    nav_profile: 'Profile',
    
    feed_new: 'New',
    feed_hot: 'Hot',
    feed_loading: 'Loading beats...',
    feed_search_placeholder: 'Search tracks, artists, genres...',
    feed_no_results: 'No tracks found for that search.',
    feed_empty: 'No tracks found. Upload the first one!',
    
    track_share: 'Share Track',
    track_copied: 'Copied!',
    track_download: 'Download Audio',
    track_downloading: 'Downloading...',
    track_delete: 'Delete',
    track_delete_confirm: 'Are you sure you want to delete this track?',
    track_listen_text: 'Listen to',
    track_by: 'by',
    track_plays: 'plays',
    track_comment_placeholder: 'Add a comment...',
    track_comment_post: 'Post',
    track_no_comments: 'No comments yet.',
    track_add_playlist: 'Add to Playlist',
    track_added_playlist: 'Added to Playlist',
    track_view_lyrics: 'Show Lyrics',
    track_no_lyrics: 'No lyrics available for this track.',
    
    snippet_promo: 'Visual card for your stories',
    snippet_save: 'Save',
    snippet_send: 'Send',
    snippet_close: 'Close Preview',
    snippet_title: 'Visual Snippet',
    
    charts_title: 'Top Charts',
    charts_week: 'Top of Week',
    charts_month: 'Top of Month',
    charts_loading: 'Loading charts...',
    charts_empty: 'Not enough data yet.',
    
    upload_title: 'Upload',
    upload_mode_single: 'Single Track',
    upload_mode_album: 'Album / EP',
    upload_cover_change: 'Change',
    upload_cover_add: 'Add Cover',
    upload_audio_remove: 'Remove',
    upload_audio_placeholder: 'Select Audio',
    upload_audio_multi_placeholder: 'Select Tracks',
    upload_label_title: 'Title',
    upload_label_album_title: 'Album Title',
    upload_placeholder_title: 'Track Name',
    upload_placeholder_album_title: 'Album Name',
    upload_label_genre: 'Genre',
    upload_label_desc: 'Description',
    upload_label_lyrics: 'Lyrics / Text',
    upload_placeholder_desc: 'Tell us about your release...',
    upload_placeholder_lyrics: 'Paste track text here...',
    upload_btn: 'Publish',
    upload_btn_album: 'Publish Album',
    upload_btn_loading: 'Uploading...',
    upload_btn_loading_album: 'Uploading Album...',
    upload_access_denied: 'Access Denied',
    upload_sub_required: 'Subscribe to our channel to upload',
    upload_sub_btn: 'Subscribe Now?',
    upload_magic_ai: 'Magic AI',
    
    profile_loading: 'Loading profile...',
    profile_not_found: 'User not found',
    profile_tracks: 'Tracks',
    profile_likes: 'Likes',
    profile_history: 'History',
    profile_playlists: 'Playlists',
    profile_saved_playlists: 'Saved Playlists',
    profile_create_playlist: 'New Playlist',
    profile_playlist_name: 'Playlist Name',
    profile_playlist_create_btn: 'Create',
    profile_playlist_cancel: 'Cancel',
    profile_playlist_save: 'Save to Library',
    profile_playlist_unsave: 'Remove from Library',
    profile_plays: 'Plays',
    profile_no_links: 'No links.',
    profile_my_tracks: 'My Tracks',
    profile_user_tracks: "'s Tracks",
    profile_no_tracks: 'No tracks.',
    profile_no_playlists: 'No playlists.',
    profile_no_saved_playlists: 'No saved playlists.',
    profile_bio_placeholder: 'Add a bio...',
    profile_no_bio: 'No bio.',
    profile_artist_hub: 'Artist Hub',
    profile_history_empty: 'Empty history',
    profile_playlist_empty: 'No tracks here',
    
    settings_title: 'Edit Profile',
    settings_language: 'Language',
    settings_header: 'Profile Header',
    settings_header_add: 'Add Image',
    settings_avatar_hint: 'Tap to change photo',
    settings_public_info: 'Public Info',
    settings_firstname: 'First Name',
    settings_lastname: 'Last Name',
    settings_bio: 'Bio',
    settings_bio_placeholder: 'About you...',
    settings_socials: 'Social Links',
    settings_other_placeholder: 'Other (VK, YouTube)',
    settings_save: 'Save',
    settings_saving: 'Saving...',
    settings_error: 'Failed to save.',

    link_spotify: 'Spotify',
    link_soundcloud: 'SoundCloud',
    link_yandex: 'Yandex Music',
    link_vk: 'VK',
    link_youtube: 'YouTube',
    link_website: 'Website',

    // Concerts
    concerts_title: 'Live Rooms',
    concerts_subtitle: 'Join real-time listening sessions',
    concerts_live_now: 'Happening Now',
    concerts_empty: 'No live rooms yet. Start your own concert!',
    concerts_create: 'Start Session',
    concerts_create_cover: 'Room Artwork',
    concerts_create_label_track: 'Opening Track',
    concerts_create_option_none: 'No track selected',
    concerts_create_btn: 'Launch Room',
    concerts_viewers: 'Listeners',
    concerts_on_air: 'On Air',
    concerts_tab_chat: 'Chat',
    concerts_tab_console: 'DJ Console',
    concerts_chat_placeholder: 'Say something...',
    concerts_mic_title: 'Microphone',
    concerts_mic_desc: 'Broadcast your voice',
    concerts_library_placeholder: 'Select a playlist',
    
    // Discovery
    discovery_title: 'Mori Discovery',
    discovery_subtitle: 'Find your vibe with AI',
    discovery_placeholder: 'Describe your mood or vibe...',
    discovery_tags_title: 'Quick Vibes',
    discovery_ai_thinking: 'AI is digging the crates...',
    discovery_empty: 'No matches found. Try another prompt.',
  },
  ru: {
    app_initializing: 'Инициализация Mori',
    nav_feed: 'Лента',
    nav_charts: 'Чарты',
    nav_upload: 'Загрузка',
    nav_profile: 'Профиль',
    
    feed_new: 'Новое',
    feed_hot: 'Топ',
    feed_loading: 'Загрузка...',
    feed_search_placeholder: 'Треки, артисты, жанры...',
    feed_no_results: 'Ничего не найдено.',
    feed_empty: 'Треков пока нет.',
    
    track_share: 'Поделиться',
    track_copied: 'Скопировано!',
    track_download: 'Скачать',
    track_downloading: 'Загрузка...',
    track_delete: 'Удалить',
    track_delete_confirm: 'Вы уверены?',
    track_listen_text: 'Слушай',
    track_by: 'от',
    track_plays: 'прослушиваний',
    track_comment_placeholder: 'Написать...',
    track_comment_post: 'Отпр.',
    track_no_comments: 'Комментариев нет.',
    track_add_playlist: 'В плейлист',
    track_added_playlist: 'Добавлено',
    track_view_lyrics: 'Текст трека',
    track_no_lyrics: 'Текст для этого трека отсутствует.',
    
    snippet_promo: 'Карточка для твоих сторис',
    snippet_save: 'Сохранить',
    snippet_send: 'Отправить',
    snippet_close: 'Закрыть',
    snippet_title: 'Сниппет',
    
    charts_title: 'Топ Чарты',
    charts_week: 'Неделя',
    charts_month: 'Месяц',
    charts_loading: 'Загрузка...',
    charts_empty: 'Данных пока нет.',
    
    upload_title: 'Загрузка',
    upload_mode_single: 'Сингл',
    upload_mode_album: 'Альбом',
    upload_cover_change: 'Изменить',
    upload_cover_add: 'Обложка',
    upload_audio_remove: 'Удалить',
    upload_audio_placeholder: 'MP3/WAV файл',
    upload_audio_multi_placeholder: 'Выбрать треки',
    upload_label_title: 'Название',
    upload_label_album_title: 'Альбом',
    upload_placeholder_title: 'Название трека',
    upload_placeholder_album_title: 'Название альбома',
    upload_label_genre: 'Жанр',
    upload_label_desc: 'Описание',
    upload_label_lyrics: 'Текст трека',
    upload_placeholder_desc: 'О релизе...',
    upload_placeholder_lyrics: 'Вставьте текст песни здесь...',
    upload_btn: 'Опубликовать',
    upload_btn_album: 'Загрузить альбом',
    upload_btn_loading: 'Загрузка...',
    upload_btn_loading_album: 'Загрузка альбома...',
    upload_access_denied: 'Доступ запрещен',
    upload_sub_required: 'Нужна подписка на канал',
    upload_magic_ai: 'Магия AI',
    upload_sub_btn: 'Подписаться?',
    
    profile_loading: 'Загрузка...',
    profile_not_found: 'Не найден',
    profile_tracks: 'Треки',
    profile_likes: 'Лайки',
    profile_history: 'История',
    profile_playlists: 'Плейлисты',
    profile_saved_playlists: 'Сохраненные',
    profile_create_playlist: 'Новый плейлист',
    profile_playlist_name: 'Название',
    profile_playlist_create_btn: 'Создать',
    profile_playlist_cancel: 'Отмена',
    profile_playlist_save: 'Сохранить',
    profile_playlist_unsave: 'Удалить',
    profile_plays: 'Прослушивания',
    profile_no_links: 'Ссылок нет.',
    profile_my_tracks: 'Мои треки',
    profile_user_tracks: ': Треки',
    profile_no_tracks: 'Пусто.',
    profile_no_playlists: 'Нет плейлистов.',
    profile_no_saved_playlists: 'Ничего не сохранено.',
    profile_bio_placeholder: 'Добавь описание...',
    profile_no_bio: 'Нет описания.',
    profile_artist_hub: 'Хаб артиста',
    profile_history_empty: 'История пуста',
    profile_playlist_empty: 'Здесь пусто',
    
    settings_title: 'Настройки',
    settings_language: 'Язык',
    settings_header: 'Шапка профиля',
    settings_header_add: 'Добавить',
    settings_avatar_hint: 'Нажми для смены фото',
    settings_public_info: 'Инфо',
    settings_firstname: 'Имя',
    settings_lastname: 'Фамилия',
    settings_bio: 'О себе',
    settings_bio_placeholder: 'О твоей музыке...',
    settings_socials: 'Соцсети',
    settings_other_placeholder: 'Другое',
    settings_save: 'Сохранить',
    settings_saving: 'Сохранение...',
    settings_error: 'Ошибка.',

    link_spotify: 'Spotify',
    link_soundcloud: 'SoundCloud',
    link_yandex: 'Яндекс Музыка',
    link_vk: 'ВКонтакте',
    link_youtube: 'YouTube',
    link_website: 'Вебсайт',

    // Concerts (Russian)
    concerts_title: 'Концерты',
    concerts_subtitle: 'Слушай музыку вместе в реальном времени',
    concerts_live_now: 'В эфире сейчас',
    concerts_empty: 'Активных комнат нет. Стань первым диджеем!',
    concerts_create: 'Создать комнату',
    concerts_create_cover: 'Обложка комнаты',
    concerts_create_label_track: 'Начальный трек',
    concerts_create_option_none: 'Без трека',
    concerts_create_btn: 'Запустить',
    concerts_viewers: 'Слушателей',
    concerts_on_air: 'В эфире',
    concerts_tab_chat: 'Чат',
    concerts_tab_console: 'Пульт',
    concerts_chat_placeholder: 'Напишите что-нибудь...',
    concerts_mic_title: 'Микрофон',
    concerts_mic_desc: 'Ваш голос в эфире',
    concerts_library_placeholder: 'Выберите плейлист',
    
    // Discovery (Russian)
    discovery_title: 'Mori Discovery',
    discovery_subtitle: 'Найди свой вайб с помощью AI',
    discovery_placeholder: 'Опиши свой настрой или вайб...',
    discovery_tags_title: 'Быстрые вайбы',
    discovery_ai_thinking: 'AI подбирает треки...',
    discovery_empty: 'Ничего не найдено. Попробуй другой запрос.',
  }
};
